/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "file.h"


void
file_transfer_prog_1(char *host, char *filename)
{
	CLIENT *clnt;
	int  *result_1;
	file  transfer_file_1_arg;
	FILE *file;

#ifndef	DEBUG
	clnt = clnt_create(host, FILE_TRANSFER_PROG, FILE_TRANSFER_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror(host);
		exit (1);
	}
#endif	/* DEBUG */

	file = fopen(filename, "r");
	if (file == NULL) {
    		printf("The file is null");
    		exit(1);
	} else {
		printf("Read file successfully\n");
	}
	
	while (1) {
	transfer_file_1_arg.buffer_size = fread(transfer_file_1_arg.buffer, 1, 1024, file);
	
	result_1 = transfer_file_1(&transfer_file_1_arg, clnt);
	if (result_1 == (int *)NULL) {
		clnt_perror(clnt, "Error uploading file");
	}
	if (transfer_file_1_arg.buffer_size < 1024) {
		printf("Upload finished!");
		break;
	}
    }
    printf("File sent!");
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int main (int argc, char *argv[])
{
	char *host;
	char *filename;

	if (argc < 3) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	filename = argv[2];
	file_transfer_prog_1 (host, filename);
	exit (0);
}
